# Generated by Django 2.1.2 on 2019-04-01 07:22

import apps.lines.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default=apps.lines.models.create_line_id, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default=apps.lines.models.create_route_id, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
