# Generated by Django 2.1.2 on 2019-03-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_2019329225626328f727f', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_20193292256260773b211', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
