# Generated by Django 2.1.2 on 2019-03-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_auto_20190329_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_2019329225851b09d77bf', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_2019329225851ddaa0ccf', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
