# Generated by Django 2.1.2 on 2019-03-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0003_auto_20190329_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_201932923271132e6693d', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_20193292327112490f3fe', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
