# Generated by Django 2.1.2 on 2019-03-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0004_auto_20190329_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_2019329233437242a3dcd', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_20193292334371c1a86d9', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
