# Generated by Django 2.1.2 on 2019-03-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0005_auto_20190329_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_201932923375765dcc7a3', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_2019329233757d0d803e5', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
