# Generated by Django 2.0.4 on 2018-10-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_own_urbvan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_user',
            field=models.IntegerField(blank=True),
        ),
    ]
