# Generated by Django 2.0.4 on 2018-10-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_own_urbvan', '0002_auto_20181019_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
