# Generated by Django 2.1.2 on 2019-04-26 23:09

import apps.lines.models.lines
import apps.lines.models.routes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineModel',
            fields=[
                ('id', models.CharField(default=apps.lines.models.lines.create_line_id, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('id', models.CharField(default=apps.lines.models.routes.create_route_id, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('direction', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lines.LineModel')),
                ('stations', models.ManyToManyField(to='stations.StationModel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
