# Generated by Django 2.1.2 on 2019-04-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_201942422182898495e5c', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_20194242218285c9bb9a9', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
