# Generated by Django 2.1.2 on 2019-04-25 23:57

import apps.lines.models.lines
import apps.lines.models.routes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linemodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='routemodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default=apps.lines.models.lines.create_line_id, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default=apps.lines.models.routes.create_route_id, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
