# Generated by Django 2.1.2 on 2019-04-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0003_auto_20190424_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_201942422251162405f13', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_201942422251101725118', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
