# Generated by Django 2.1.2 on 2019-04-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0005_auto_20190424_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_2019424222843fe1c22bb', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_2019424222843e169be28', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
