# Generated by Django 2.1.2 on 2019-04-01 07:22

import apps.stations.models.locations
import apps.stations.models.stations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default=apps.stations.models.locations.create_location_id, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default=apps.stations.models.stations.create_station_id, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
