# Generated by Django 2.1.2 on 2019-03-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20190329_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_20193292258510325c473', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_20193292258512443fd8d', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
