# Generated by Django 2.1.2 on 2019-03-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_auto_20190329_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_20193292334377ad41c6f', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_201932923343714ebb17a', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
