# Generated by Django 2.1.2 on 2019-11-16 20:40

import apps.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineModel',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.CharField(db_index=True, default=apps.utils.IDGenerator, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.CharField(default=apps.utils.IDGenerator, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('direction', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='routes', to='lines.LineModel')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
