# Generated by Django 2.0.4 on 2018-08-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_2018816227443ff5a204', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_201881622744c38d3267', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
