# Generated by Django 2.1.2 on 2019-11-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routemodel',
            name='stations',
            field=models.ManyToManyField(to='stations.StationModel'),
        ),
    ]
