# Generated by Django 2.1.2 on 2019-11-15 01:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lines", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="linemodel", options={"ordering": ["-id"]},),
        migrations.AlterModelOptions(name="routemodel", options={"ordering": ["-id"]},),
        migrations.AddField(
            model_name="linemodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="linemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="routemodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="routemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="linemodel",
            name="id",
            field=models.CharField(
                default="line_20191115137251ab728d9",
                max_length=30,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="routemodel",
            name="id",
            field=models.CharField(
                default="route_201911151372527fadeca",
                max_length=30,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="routemodel",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lines.LineModel"
            ),
        ),
    ]
