# Generated by Django 2.0.4 on 2018-05-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_auto_20180502_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='color',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.AutoField(auto_created=True, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.AutoField(auto_created=True, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
