# Generated by Django 2.0.4 on 2018-10-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_auto_20181009_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_2018101003654bd0b6ca9', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_201810100365467ef1344', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
