# Generated by Django 2.1.2 on 2019-11-16 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lines', '0002_routemodel_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='routemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_route', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_line', to=settings.AUTH_USER_MODEL),
        ),
    ]
