# Generated by Django 2.1.2 on 2019-11-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_auto_20191115_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_201911167492423742a01', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_2019111674924d63581d5', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='routes', to='lines.LineModel'),
        ),
    ]
