# Generated by Django 2.0.4 on 2018-10-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0003_auto_20181010_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_201810191741321cabdb10', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_20181019174132c26b72ea', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
