# Generated by Django 2.0.4 on 2018-10-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0004_auto_20181019_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_20181019174608f2573c4', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_2018101917460cf260100', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
