# Generated by Django 2.0.4 on 2018-10-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0005_auto_20181019_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_201810191746326ae36315', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_201810191746321a5cade7', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
