# Generated by Django 2.0.4 on 2018-10-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0006_auto_20181019_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_201810191951170beebe13', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_20181019195117e38d390f', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
