# Generated by Django 2.1.2 on 2019-11-15 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.CharField(default='loc_20191115205310c69d28b4', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('id', models.CharField(default='sta_20191115205310704b45df', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stations.LocationModel')),
            ],
        ),
    ]
