# Generated by Django 2.0.4 on 2018-05-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.AutoField(auto_created=True, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.AutoField(auto_created=True, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
