# Generated by Django 2.0.4 on 2018-08-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_2018816227448751d36d', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_201881622744930deeac', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
