# Generated by Django 2.1.2 on 2019-11-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_20191116216332a321d57', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_201911162163302bbf0f4', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
