# Generated by Django 2.1.2 on 2019-11-15 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historical",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[("Delete", "delete"), ("Create", "create")],
                        default="Delete",
                        max_length=100,
                    ),
                ),
                ("model_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="locationmodel", options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="stationmodel", options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="stationmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stationmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="locationmodel",
            name="id",
            field=models.CharField(
                default="loc_2019111513725ab66294b",
                max_length=30,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="stationmodel",
            name="id",
            field=models.CharField(
                default="sta_2019111513725f6fce71c",
                max_length=30,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
