# Generated by Django 2.1.2 on 2019-11-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_201911161108d1eb6ccb', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_201911161108b71c7aba', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
