# Generated by Django 2.0.4 on 2018-04-29 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion', null=True),
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion', null=True),
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='user_create',
            field=models.ForeignKey(default=1, help_text='Usuario que crea el registro', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_201842919492121274964', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_20184291949218b49ac53', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
