# Generated by Django 2.0.4 on 2018-04-29 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20180429_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='key',
            field=models.CharField(default='CMX', help_text='Clave conformada por 3 primeras letras', max_length=4, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_2018429203119b7d1d35', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten caracteres en este campo', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_201842920311f92de428', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
