# Generated by Django 2.1.2 on 2019-11-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20191115_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_2019111674924dae7ba95', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_20191116749249a1def06', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
