# Generated by Django 2.1.2 on 2019-07-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20190710_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_2019711344460fcc6de5', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_2019711344469e46c0a9', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
