# Generated by Django 2.0.4 on 2018-05-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20180503_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmodel',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
