# Generated by Django 2.0.4 on 2018-10-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20181009_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_2018101003654014c1dd3', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_2018101003654b42d8c89', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
