# Generated by Django 2.0.4 on 2018-10-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_auto_20181019_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_2018101919511741f5bc17', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_20181019195117682b8700', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
