# Generated by Django 2.1.2 on 2019-04-27 00:53

import apps.stations.models.locations
import apps.stations.models.stations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.CharField(default=apps.stations.models.locations.create_location_id, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('id', models.CharField(default=apps.stations.models.stations.create_station_id, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stations', to='stations.LocationModel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
