# Generated by Django 2.1.2 on 2019-04-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20190424_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_2019424222423cd397f85', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_20194242224233ec0c4d1', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
