# Generated by Django 2.1.2 on 2019-04-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_auto_20190424_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_201942422254351cacb3e', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_201942422254316dad152', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
