# Generated by Django 2.1.2 on 2019-04-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_auto_20190424_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_201942422284392ec8145', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_20194242228435b902eef', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
