# Generated by Django 2.1.2 on 2018-12-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Supervisor'), (2, 'Driver'), (3, 'Passenger')], default=3),
        ),
    ]
